import 'dart:convert';
import 'dart:typed_data';

// ============================================================
// VEIL CODEC — fnv_lcg family (generated by tool/forge)
// ============================================================
// Do NOT hand-edit. Regenerate via `dart run tool/forge/mint.dart`.
// ============================================================

const List<int> _saltBytes = <int>[
  0xCD, 0xC8, 0x2A, 0xFD, 0x81, 0xBA, 0x06, 0x3E,
  0xA1, 0x1F, 0x1B, 0x6E, 0xC1, 0x7A, 0xC4, 0xAC,
  0x5C,
];
const int _streamLen = 26;

int _fnv1a(List<int> data) {
  int hash = 0x811C9DC5;
  for (final int c in data) {
    hash = (hash ^ c) & 0xFFFFFFFF;
    hash = (hash * 0x01000193) & 0xFFFFFFFF;
  }
  return hash == 0 ? 0x9E3779B9 : hash;
}

Uint8List _keystream() {
  int state = _fnv1a(_saltBytes);
  final Uint8List out = Uint8List(_streamLen);
  for (int i = 0; i < _streamLen; i++) {
    state = (state * 1664525 + 1013904223) & 0xFFFFFFFF;
    out[i] = (state >> 24) & 0xFF;
  }
  return out;
}

final Uint8List _stream = _keystream();

String reveal(List<int> encoded) {
  if (encoded.isEmpty) return '';
  final Uint8List out = Uint8List(encoded.length);
  for (int i = 0; i < encoded.length; i++) {
    out[i] = (encoded[i] ^ _stream[i % _streamLen]) & 0xFF;
  }
  return utf8.decode(out);
}
