// ============================================================
// Codec template + encoder — fnv_lcg
// ============================================================
// Family: FNV-1a hash of a UTF-8 salt string → LCG (Numerical
// Recipes: 1664525, 1013904223) keystream → per-byte XOR with
// keystream[i % len]. NO positionMask, NO xorshift. Different
// cluster shape than `position_xor`.
// ============================================================

import 'dart:convert';
import 'dart:typed_data';

int _fnv1aOfBytes(List<int> data) {
  int hash = 0x811C9DC5;
  for (final int c in data) {
    hash = (hash ^ c) & 0xFFFFFFFF;
    hash = (hash * 0x01000193) & 0xFFFFFFFF;
  }
  return hash == 0 ? 0x9E3779B9 : hash;
}

Uint8List _buildStream(List<int> salt, int streamLen) {
  int state = _fnv1aOfBytes(salt);
  final Uint8List out = Uint8List(streamLen);
  for (int i = 0; i < streamLen; i++) {
    state = (state * 1664525 + 1013904223) & 0xFFFFFFFF;
    out[i] = (state >> 24) & 0xFF;
  }
  return out;
}

List<int> encodeFnvLcg({
  required String plain,
  required List<int> salt,
  required int streamLen,
}) {
  if (plain.isEmpty) return const <int>[];
  final Uint8List stream = _buildStream(salt, streamLen);
  final List<int> src = utf8.encode(plain);
  final Uint8List out = Uint8List(src.length);
  for (int i = 0; i < src.length; i++) {
    out[i] = (src[i] ^ stream[i % streamLen]) & 0xFF;
  }
  return out;
}

bool roundTripsFnvLcg({
  required String plain,
  required List<int> salt,
  required int streamLen,
}) {
  final List<int> encoded = encodeFnvLcg(
    plain: plain,
    salt: salt,
    streamLen: streamLen,
  );
  final Uint8List stream = _buildStream(salt, streamLen);
  final Uint8List out = Uint8List(encoded.length);
  for (int i = 0; i < encoded.length; i++) {
    out[i] = (encoded[i] ^ stream[i % streamLen]) & 0xFF;
  }
  return utf8.decode(out) == plain;
}

String fnvLcgRuntimeSource({
  required List<int> salt,
  required int streamLen,
}) =>
    _template
        .replaceFirst('__SALT__', _formatBytes(salt))
        .replaceFirst('__STREAM_LEN__', streamLen.toString());

String _formatBytes(List<int> bytes) {
  final StringBuffer buf = StringBuffer('<int>[\n');
  for (int i = 0; i < bytes.length; i++) {
    if (i % 8 == 0) buf.write('  ');
    buf.write('0x${bytes[i].toRadixString(16).toUpperCase().padLeft(2, '0')}');
    buf.write(',');
    if (i % 8 == 7 || i == bytes.length - 1) {
      buf.write('\n');
    } else {
      buf.write(' ');
    }
  }
  buf.write(']');
  return buf.toString();
}

const String _template = r"""
import 'dart:convert';
import 'dart:typed_data';

// ============================================================
// VEIL CODEC — fnv_lcg family (generated by tool/forge)
// ============================================================
// Do NOT hand-edit. Regenerate via `dart run tool/forge/mint.dart`.
// ============================================================

const List<int> _saltBytes = __SALT__;
const int _streamLen = __STREAM_LEN__;

int _fnv1a(List<int> data) {
  int hash = 0x811C9DC5;
  for (final int c in data) {
    hash = (hash ^ c) & 0xFFFFFFFF;
    hash = (hash * 0x01000193) & 0xFFFFFFFF;
  }
  return hash == 0 ? 0x9E3779B9 : hash;
}

Uint8List _keystream() {
  int state = _fnv1a(_saltBytes);
  final Uint8List out = Uint8List(_streamLen);
  for (int i = 0; i < _streamLen; i++) {
    state = (state * 1664525 + 1013904223) & 0xFFFFFFFF;
    out[i] = (state >> 24) & 0xFF;
  }
  return out;
}

final Uint8List _stream = _keystream();

String reveal(List<int> encoded) {
  if (encoded.isEmpty) return '';
  final Uint8List out = Uint8List(encoded.length);
  for (int i = 0; i < encoded.length; i++) {
    out[i] = (encoded[i] ^ _stream[i % _streamLen]) & 0xFF;
  }
  return utf8.decode(out);
}
""";
