// ============================================================
// Codec template + encoder — position_xor
// ============================================================
// Runtime file lives at `lib/caldera/mask/codec.dart`.
// The template below is written by `tool/forge/mint.dart` when
// the recipe selects `family: "position_xor"`. The encoder is
// used by mint.dart to produce the byte arrays that go into
// `lib/caldera/brief/hidden.dart`.
//
// Family: additive salt fold → xorshift32 keystream → per-byte
//         XOR against keystream[i%len] XOR positionMask(i).
// Cluster shape: keystream generation is a Weyl-style additive
//   accumulator (no multiplication overflow on 32-bit Web).
// ============================================================

import 'dart:convert';
import 'dart:typed_data';

const int _weylStep = 0x9E3779B1;

Uint8List _buildStream(List<int> salt, int streamLen) {
  int acc = 0x243F6A88;
  for (int i = 0; i < salt.length; i++) {
    acc = (acc + salt[i] * (i + 1) + _weylStep) & 0xFFFFFFFF;
  }
  int state = acc == 0 ? _weylStep : acc;
  final Uint8List stream = Uint8List(streamLen);
  for (int i = 0; i < streamLen; i++) {
    state ^= (state << 13) & 0xFFFFFFFF;
    state ^= state >> 17;
    state ^= (state << 5) & 0xFFFFFFFF;
    state &= 0xFFFFFFFF;
    stream[i] = (state >> 16) & 0xFF;
  }
  return stream;
}

int _positionMask(int i) => ((i * _weylStep) >> 16) & 0xFF;

/// Encodes [plain] to the byte-array form consumed by `reveal()`
/// in `lib/caldera/mask/codec.dart`.
List<int> encodePositionXor({
  required String plain,
  required List<int> salt,
  required int streamLen,
}) {
  if (plain.isEmpty) return const <int>[];
  final Uint8List stream = _buildStream(salt, streamLen);
  final List<int> src = utf8.encode(plain);
  final Uint8List out = Uint8List(src.length);
  for (int i = 0; i < src.length; i++) {
    out[i] = (src[i] ^ stream[i % streamLen] ^ _positionMask(i)) & 0xFF;
  }
  return out;
}

/// Verifies a round-trip. Used by mint.dart before writing.
bool roundTripsPositionXor({
  required String plain,
  required List<int> salt,
  required int streamLen,
}) {
  final List<int> encoded = encodePositionXor(
    plain: plain,
    salt: salt,
    streamLen: streamLen,
  );
  final Uint8List stream = _buildStream(salt, streamLen);
  final Uint8List out = Uint8List(encoded.length);
  for (int i = 0; i < encoded.length; i++) {
    out[i] = (encoded[i] ^ stream[i % streamLen] ^ _positionMask(i)) & 0xFF;
  }
  return utf8.decode(out) == plain;
}

/// The literal Dart source that goes into
/// `lib/caldera/mask/codec.dart`, parametrised by salt + len.
/// Kept in-file so the codec family + its encoder never drift.
String positionXorRuntimeSource({
  required List<int> salt,
  required int streamLen,
}) =>
    _positionXorRuntimeTemplate
        .replaceFirst('__SALT__', _formatBytes(salt))
        .replaceFirst('__STREAM_LEN__', streamLen.toString());

String _formatBytes(List<int> bytes) {
  final StringBuffer buf = StringBuffer('<int>[\n');
  for (int i = 0; i < bytes.length; i++) {
    if (i % 8 == 0) buf.write('  ');
    buf.write('0x${bytes[i].toRadixString(16).toUpperCase().padLeft(2, '0')}');
    buf.write(',');
    if (i % 8 == 7 || i == bytes.length - 1) {
      buf.write('\n');
    } else {
      buf.write(' ');
    }
  }
  buf.write(']');
  return buf.toString();
}

const String _positionXorRuntimeTemplate = r"""
import 'dart:convert';
import 'dart:typed_data';

// ============================================================
// VEIL CODEC — position_xor family (generated by tool/forge)
// ============================================================
// Do NOT hand-edit. Regenerate via `dart run tool/forge/mint.dart`.
// ============================================================

const List<int> _saltBytes = __SALT__;
const int _streamLen = __STREAM_LEN__;

const int _weylStep = 0x9E3779B1;

Uint8List _keystream() {
  int accumulator = 0x243F6A88;
  for (int i = 0; i < _saltBytes.length; i++) {
    accumulator = (accumulator + _saltBytes[i] * (i + 1) + _weylStep) &
        0xFFFFFFFF;
  }
  int state = accumulator == 0 ? _weylStep : accumulator;
  final Uint8List stream = Uint8List(_streamLen);
  for (int i = 0; i < _streamLen; i++) {
    state ^= (state << 13) & 0xFFFFFFFF;
    state ^= state >> 17;
    state ^= (state << 5) & 0xFFFFFFFF;
    state &= 0xFFFFFFFF;
    stream[i] = (state >> 16) & 0xFF;
  }
  return stream;
}

final Uint8List _stream = _keystream();

int _positionMask(int i) => ((i * _weylStep) >> 16) & 0xFF;

String reveal(List<int> encoded) {
  if (encoded.isEmpty) return '';
  final Uint8List out = Uint8List(encoded.length);
  for (int i = 0; i < encoded.length; i++) {
    out[i] = (encoded[i] ^ _stream[i % _streamLen] ^ _positionMask(i)) & 0xFF;
  }
  return utf8.decode(out);
}
""";
