// ============================================================
// Codec template + encoder — rc4_ksa
// ============================================================
// Family: RC4-style key-scheduling + PRGA over the salt bytes.
// This codec exists precisely to sit in a DIFFERENT cluster than
// `position_xor` and `fnv_lcg` — its data-flow graph is well-known
// to store scanners (two nested 256-entry loops mutating a state
// array), so use sparingly. `.cursor/rules/relay_forge.md` §Cipher
// families explains when this is the correct choice.
// ============================================================

import 'dart:convert';
import 'dart:typed_data';

Uint8List _prga(List<int> salt, int outputLen) {
  final Uint8List state = Uint8List(256);
  for (int i = 0; i < 256; i++) {
    state[i] = i;
  }
  int j = 0;
  for (int i = 0; i < 256; i++) {
    j = (j + state[i] + salt[i % salt.length]) & 0xFF;
    final int tmp = state[i];
    state[i] = state[j];
    state[j] = tmp;
  }
  int a = 0;
  int b = 0;
  final Uint8List out = Uint8List(outputLen);
  for (int k = 0; k < outputLen; k++) {
    a = (a + 1) & 0xFF;
    b = (b + state[a]) & 0xFF;
    final int tmp = state[a];
    state[a] = state[b];
    state[b] = tmp;
    out[k] = state[(state[a] + state[b]) & 0xFF];
  }
  return out;
}

List<int> encodeRc4Ksa({
  required String plain,
  required List<int> salt,
  required int streamLen, // ignored; RC4 keystream length == plain length
}) {
  if (plain.isEmpty) return const <int>[];
  final List<int> src = utf8.encode(plain);
  final Uint8List key = _prga(salt, src.length);
  final Uint8List out = Uint8List(src.length);
  for (int i = 0; i < src.length; i++) {
    out[i] = (src[i] ^ key[i]) & 0xFF;
  }
  return out;
}

bool roundTripsRc4Ksa({
  required String plain,
  required List<int> salt,
  required int streamLen,
}) {
  final List<int> encoded = encodeRc4Ksa(
    plain: plain,
    salt: salt,
    streamLen: streamLen,
  );
  final Uint8List key = _prga(salt, encoded.length);
  final Uint8List out = Uint8List(encoded.length);
  for (int i = 0; i < encoded.length; i++) {
    out[i] = (encoded[i] ^ key[i]) & 0xFF;
  }
  return utf8.decode(out) == plain;
}

String rc4KsaRuntimeSource({
  required List<int> salt,
  required int streamLen,
}) =>
    _template.replaceFirst('__SALT__', _formatBytes(salt));

String _formatBytes(List<int> bytes) {
  final StringBuffer buf = StringBuffer('<int>[\n');
  for (int i = 0; i < bytes.length; i++) {
    if (i % 8 == 0) buf.write('  ');
    buf.write('0x${bytes[i].toRadixString(16).toUpperCase().padLeft(2, '0')}');
    buf.write(',');
    if (i % 8 == 7 || i == bytes.length - 1) {
      buf.write('\n');
    } else {
      buf.write(' ');
    }
  }
  buf.write(']');
  return buf.toString();
}

const String _template = r"""
import 'dart:convert';
import 'dart:typed_data';

// ============================================================
// VEIL CODEC — rc4_ksa family (generated by tool/forge)
// ============================================================
// Do NOT hand-edit. Regenerate via `dart run tool/forge/mint.dart`.
// ============================================================

const List<int> _saltBytes = __SALT__;

Uint8List _prga(int n) {
  final Uint8List state = Uint8List(256);
  for (int i = 0; i < 256; i++) {
    state[i] = i;
  }
  int j = 0;
  for (int i = 0; i < 256; i++) {
    j = (j + state[i] + _saltBytes[i % _saltBytes.length]) & 0xFF;
    final int tmp = state[i];
    state[i] = state[j];
    state[j] = tmp;
  }
  int a = 0;
  int b = 0;
  final Uint8List out = Uint8List(n);
  for (int k = 0; k < n; k++) {
    a = (a + 1) & 0xFF;
    b = (b + state[a]) & 0xFF;
    final int tmp = state[a];
    state[a] = state[b];
    state[b] = tmp;
    out[k] = state[(state[a] + state[b]) & 0xFF];
  }
  return out;
}

String reveal(List<int> encoded) {
  if (encoded.isEmpty) return '';
  final Uint8List key = _prga(encoded.length);
  final Uint8List out = Uint8List(encoded.length);
  for (int i = 0; i < encoded.length; i++) {
    out[i] = (encoded[i] ^ key[i]) & 0xFF;
  }
  return utf8.decode(out);
}
""";
